enum Getters {
  COMPLETED_TO_DOS = "COMPLETED_TO_DOS",
  INCOMPLETE_TO_DOS = "INCOMPLETE_TO_DOS",
  PERCENTAGE_COMPLETE = "PERCENTAGE_COMPLETE",
  GET_LISTS = "GET_LISTS",
  CURRENT_LIST_TITLE = "CURRENT_LIST_TITLE",
}

export default Getters
